<a href="https://colab.research.google.com/github/kaniela04/Detection_Of_Harmful_Objects-Neural_Network/blob/main/part1_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

*IMPORTAR LIRERIAS*

torch = PyTorch
numpy = base matemática

La guía dice que PyTorch funciona como NumPy pero para redes neuronales

In [1]:
import torch 
import numpy as np 

*CREAR TENSORES*

Un tensor es la base de todo: 
vector-1D
Matriz-2D
imageb-3D

En la guia los tensores son la base fundamental de las redes neuronales, creamos un tensor x de tamaño 3x2 con valores aleatorios entre 0 y 1.

In [2]:
x = torch.rand(3,2)
print("Tensor x:") 
print(x)

Tensor x:
tensor([[0.8027, 0.8392],
        [0.3406, 0.6103],
        [0.2932, 0.7247]])


*OPERACIONES*
las redes neuronales hacen sumas y multiplicaciones, se crea un tensor y del mismo tamaño que x, pero en este caso sera lleno de unos y tambien Se suman los tensores x | y de forma elemento a elemento.

In [ ]:
y= torch.ones (x.size())
print("Tensor y:")
print(y)
z= x + y 
print("Tensor z = x + y:")
print(z)


Tensor y:
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
Tensor z = x + y:
tensor([[1.7214, 1.9522],
        [1.5545, 1.4798],
        [1.7150, 1.5089]])


*INDEXACIÒN* 
Esto es importante porque segun la guia con esto podemos aceder a datos especificos, en donde el entrenamiento de la neurona: 

- sleccionar pixeles 
- seleccioar features 

In [ ]:
print(z[0])
print(z[:, 1])

tensor([1.0418, 1.7151])
tensor([1.7151, 1.9395, 1.2886])


*OPERACIONES IN-PLACE*

Usamos _ para modificar el tensor original y esimportante en optimizacion (memoria y velociidad)

In [ ]:
print("Sumando 1 a cada elemento de 'z':")
print("Actualizacion tensor z con z.add_(1)")
z.add_(1)

Sumando 1 a cada elemento de 'z':
Actualizacion tensor z con z.add_(1)


tensor([[2.7214, 2.9522],
        [2.5545, 2.4798],
        [2.7150, 2.5089]])

Las redes neuronales necesitan datos en formato específico y para eso usamos *RESHAPE*

Ejemplo:

Imagen: 20x20
Red: vector de 700

In [ ]:
print(" Modificamos 'z' a (2,3) con resize_:")
z.resize_(2, 3)
print(z)

 Modificamos 'z' a (2,3) con resize_:
tensor([[2.7214, 2.9522, 2.5545],
        [2.4798, 2.7150, 2.5089]])


*NUMPY ↔ TORCH*
Aqui realizamos la conversion entre Numpy y Torch, en la que se crea un array de NumPy 'a' de tamaño 4x3 con valores aleatorios, luego convierte el array de NumPy a un tensor de PyTorch 'b', despues se convierte 'b' nuevamente a un array de NumPy, multiplicamos y finalmente como 'b' y 'a' comparten la misma memoria, al modificar 'b' también se actualiza 'a'.

In [ ]:
a = np.random.rand(4,3)

b = torch.from_numpy(a)
print("Array de NumPy 'a' (4x3) con valores aleatorios")
print(a)

print("Convirtiendo 'a' a tensor de PyTorch 'b': ")
print(b)

b_new = b.numpy()
print("Se combierte 'b' nuevamente a array de NumPy (b_new):")
print(b_new)


b.mul_(2)
print("Tensor 'b' después de b.mul_(2):")
print(b)

print("Array 'a' actualizado:")
print(a)

Array de NumPy 'a' (4x3) con valores aleatorios
[[0.21476821 0.28015498 0.97100911]
 [0.47884779 0.66239135 0.31480724]
 [0.5945565  0.50952137 0.46995808]
 [0.27151781 0.22665513 0.8700482 ]]
Convirtiendo 'a' a tensor de PyTorch 'b': 
tensor([[0.2148, 0.2802, 0.9710],
        [0.4788, 0.6624, 0.3148],
        [0.5946, 0.5095, 0.4700],
        [0.2715, 0.2267, 0.8700]], dtype=torch.float64)
Se combierte 'b' nuevamente a array de NumPy (b_new):
[[0.21476821 0.28015498 0.97100911]
 [0.47884779 0.66239135 0.31480724]
 [0.5945565  0.50952137 0.46995808]
 [0.27151781 0.22665513 0.8700482 ]]
Tensor 'b' después de b.mul_(2):
tensor([[0.4295, 0.5603, 1.9420],
        [0.9577, 1.3248, 0.6296],
        [1.1891, 1.0190, 0.9399],
        [0.5430, 0.4533, 1.7401]], dtype=torch.float64)
Array 'a' actualizado:
[[0.42953642 0.56030997 1.94201822]
 [0.95769557 1.32478269 0.62961448]
 [1.18911299 1.01904273 0.93991616]
 [0.54303563 0.45331026 1.7400964 ]]
